name: flutter_video
description: Base by bilibili ijkplayer, it's video/audio player, support https、rtmp、m3u8 and more protocol.
version: 0.1.5
author: zhangbaolin<572352296@qq.com>
homepage: https://github.com/zhangbaolin/flutter_video.git

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  orientation: ^1.1.0
  screen: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: top.kikt.ijkplayer
    pluginClass: IjkplayerPlugin
